name: quiz_app
description: SFA Tools application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # lottie: ^2.2.0
  lottie: ^2.3.2
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  get: ^4.6.5
  dio: ^5.1.1
  http: ^0.13.5
  json_annotation: ^4.8.0
  hive: ^2.2.3
  path_provider: ^2.0.13
  intl: ^0.18.0
  auto_size_text: ^3.0.0
  device_info_plus: ^8.1.0
  permission_handler: ^10.2.0
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  device_apps: ^2.2.0
  package_info_plus: ^3.1.0
  workmanager: ^0.5.1
  android_alarm_manager_plus: ^2.1.2
  flutter_background_service: ^2.4.6
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
