name: quiz_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.2.0
  flutter_svg: ^1.1.6
  # flutter_svg: ^2.0.1
  # jovial_svg: ^1.1.9
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  # in_app_update: ^4.0.1
  dio: ^5.0.2
  json_annotation: ^4.8.0
  http: ^0.13.5
  # collection: ^1.16.0
  hive: ^2.2.3
  path_provider: ^2.0.13
  # platform_device_id: ^1.0.1
  intl: ^0.18.0
  auto_size_text: ^3.0.0
  # client_information: ^2.0.3+1
  # android_id: ^0.1.3+1
  device_info_plus: ^8.1.0
  permission_handler: ^10.2.0
  connectivity_plus: ^3.0.3
  open_file_plus: ^3.3.0
  percent_indicator: ^4.2.3
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  device_apps: ^2.2.0
  android_intent_plus: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
