import 'package:hive/hive.dart';

part 'penjualanpostmodel.g.dart'; // This is generated by build_runner

@HiveType(typeId: 7)
class PenjualanPostModel extends HiveObject {
  @HiveField(0)
  List<Map<String, dynamic>> dataList;

  PenjualanPostModel(this.dataList);
}
