import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

part 'vendor.g.dart'; // This will be generated by the build_runner

@JsonSerializable()
@HiveType(typeId: 5) // Unique type ID for Vendor
class Vendor extends HiveObject {
  @HiveField(0) // Unique field ID for each field
  final String prefix;
  
  @HiveField(1)
  final String name;
  
  @HiveField(2)
  final String baseApiUrl;

  Vendor({
    required this.prefix,
    required this.name,
    required this.baseApiUrl,
  });
  
  factory Vendor.fromJson(Map<String, dynamic> json) {
    return Vendor(
      prefix: json['prefix'],
      name: json['name'],
      baseApiUrl: json['baseApiUrl'],
    );
  }

  factory Vendor.from(Map<String, dynamic> json) => _$VendorFromJson(json);

  Map<String, dynamic> toJson() => _$VendorToJson(this);
}
